-- MySQL Script generated by MySQL Workbench
-- Sun Jul 14 18:03:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eventDB
-- -----------------------------------------------------
-- Cette base de donéee contient tous les evennemnet de lllc 
DROP SCHEMA IF EXISTS `eventDB` ;

-- -----------------------------------------------------
-- Schema eventDB
--
-- Cette base de donéee contient tous les evennemnet de lllc 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eventDB` DEFAULT CHARACTER SET utf8 ;
USE `eventDB` ;

-- -----------------------------------------------------
-- Table `eventDB`.`evennement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `eventDB`.`evennement` ;

CREATE TABLE IF NOT EXISTS `eventDB`.`evennement` (
  `idevennement` INT NOT NULL,
  `NomEvenement` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `date` DATE NULL,
  PRIMARY KEY (`idevennement`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
